// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.wujm.ashlar.tool;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * All nine {@code /tools/&lt;name&gt;.json} resources (generated by {@code
 * mcp-server/tools/export-specs.mjs}) load, in the same order as {@code
 * mcp-server/src/tools/index.ts}'s {@code registerAllTools}, and each description carries the
 * four-part structure (spec section 4.3 part 4: what / when to use and not / parameters or
 * coordinates / side effects).
 */
class ToolSpecTest {

    /** Same order as mcp-server/src/tools/index.ts's registerAllTools and ToolRegistry's registration in AshlarPlugin. */
    private static final List<String> EXPECTED_ORDER = List.of(
            "mc_status", "mc_players", "mc_survey", "mc_build", "mc_inspect", "mc_render", "mc_snapshot", "mc_restore", "mc_command");

    @Test
    void everyToolSpecLoadsWithMatchingName() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            assertEquals(name, spec.name());
            assertFalse(spec.title().isBlank(), name + ": title must not be blank");
            assertFalse(spec.description().isBlank(), name + ": description must not be blank");
        }
    }

    @Test
    void everyDescriptionHasTheFourSectionMarkers() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            String d = spec.description();
            assertTrue(d.contains("WHEN TO USE:"), name + ": missing WHEN TO USE section");
            assertTrue(d.contains("WHEN NOT TO USE:"), name + ": missing WHEN NOT TO USE section");
            assertTrue(d.contains("PARAMETERS:") || d.contains("COORDINATES:"), name + ": missing PARAMETERS/COORDINATES section");
            assertTrue(d.contains("SIDE EFFECTS:"), name + ": missing SIDE EFFECTS section");
        }
    }

    @Test
    void inputSchemaAndAnnotationsAreObjects() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            assertTrue(spec.inputSchema().has("type"), name + ": inputSchema missing \"type\"");
            assertTrue(spec.annotations().has("readOnlyHint"), name + ": annotations missing \"readOnlyHint\"");
        }
    }

    @Test
    void toJsonRoundTripsTheSameFields() {
        ToolSpec spec = ToolSpec.load("mc_status");
        var json = spec.toJson();
        assertEquals(spec.name(), json.get("name").getAsString());
        assertEquals(spec.title(), json.get("title").getAsString());
        assertEquals(spec.description(), json.get("description").getAsString());
    }
}
