// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.wujm.ashlar.tool;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

/**
 * One {@code mc_*} tool's client-facing definition, loaded verbatim from
 * {@code /tools/&lt;name&gt;.json} on the classpath (plan.md Step 7.2b). Those
 * resources are generated by {@code mcp-server/tools/export-specs.mjs} from
 * the live TypeScript tool registrations, so {@link #description} and
 * {@link #inputSchema} are byte-identical to what MCP clients see today -
 * the e2e description/section-header checks keep passing by construction.
 */
public record ToolSpec(String name, String title, String description, JsonObject inputSchema, JsonObject annotations) {

    /** Reads {@code /tools/<name>.json} from the classpath and parses it into a {@link ToolSpec}. */
    public static ToolSpec load(String name) {
        String resourcePath = "/tools/" + name + ".json";
        try (InputStream in = ToolSpec.class.getResourceAsStream(resourcePath)) {
            if (in == null) {
                throw new IllegalStateException("missing tool spec resource: " + resourcePath);
            }
            JsonObject json;
            try (InputStreamReader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
                json = JsonParser.parseReader(reader).getAsJsonObject();
            }
            return fromJson(json);
        } catch (IOException e) {
            throw new UncheckedIOException("failed to read tool spec resource: " + resourcePath, e);
        }
    }

    private static JsonObject orEmpty(JsonElement e) {
        return (e != null && e.isJsonObject()) ? e.getAsJsonObject() : new JsonObject();
    }

    private static ToolSpec fromJson(JsonObject json) {
        return new ToolSpec(
                json.get("name").getAsString(),
                json.get("title").getAsString(),
                json.get("description").getAsString(),
                orEmpty(json.get("inputSchema")),
                orEmpty(json.get("annotations")));
    }

    /** Reproduces the same object shape (and key order) as the source resource. */
    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        json.addProperty("name", name);
        json.addProperty("title", title);
        json.addProperty("description", description);
        json.add("inputSchema", inputSchema);
        json.add("annotations", annotations);
        return json;
    }
}
